#########################################################
-- 分别抽取train test 高低频数据集
#########################################################

CREATE TABLE IF NOT EXISTS train_low_feas AS
  SELECT event_id 
       ,new_is_fraud 
       ,amt 
       ,amt_r 
       ,card_bin_prov 
       ,card_cert_city 
       ,card_cert_prov 
       ,card_mobile_city 
       ,card_mobile_prov 
       ,cert_city 
       ,cert_myphone_c 
       ,cert_myphone_p 
       ,cert_prov 
       ,de_n_perh 
       ,de_n_perhop 
       ,deal_cnt_inf 
       ,deal_cnt_ratio 
       ,device_dif 
       ,device_opdif 
       ,device_sign 
       ,event_rank_day 
       ,event_rank_dayop 
       ,gmt_day_of_month 
       ,gmt_day_of_week 
       ,gmt_hour 
       ,h_dif 
       ,high_1_rato 
       ,high_3_rato 
       ,high_5_rato 
       ,high_7_rato 
       ,high_freq 
       ,his_high_fix 
       ,hist_amt_per 
       ,hist_card_bin_city_per 
       ,hist_card_bin_prov_per 
       ,hist_card_cert_city_per 
       ,hist_card_cert_no_per 
       ,hist_card_cert_prov_per 
       ,hist_card_mobile_city_per 
       ,hist_card_mobile_prov_per 
       ,hist_cert_city_per 
       ,hist_cert_prov_per 
       ,hist_client_ip_per 
       ,hist_device_sign_per 
       ,hist_info_1_per 
       ,hist_info_2_per 
       ,hist_ip_city_per 
       ,hist_ip_prov_per 
       ,hist_mobile_oper_platform_per 
       ,hist_network_per 
       ,hist_operation_channel_per 
       ,hist_pay_scene_per 
       ,hist_prec_amt 
       ,hist_prec_card_bin_city 
       ,hist_prec_card_bin_prov 
       ,hist_prec_card_cert_city 
       ,hist_prec_card_cert_no 
       ,hist_prec_card_cert_prov 
       ,hist_prec_card_mobile_city 
       ,hist_prec_card_mobile_prov 
       ,hist_prec_cert_city 
       ,hist_prec_cert_prov 
       ,hist_prec_city 
       ,hist_prec_client_ip 
       ,hist_prec_device_sign 
       ,hist_prec_info_1 
       ,hist_prec_info_1_income_card_no 
       ,hist_prec_info_2 
       ,hist_prec_info_2_mobile_oper_platform 
       ,hist_prec_ip_city 
       ,hist_prec_ip_prov 
       ,hist_prec_is_peer_pay 
       ,hist_prec_mobile_oper_platform 
       ,hist_prec_network 
       ,hist_prec_operation_channel 
       ,hist_prec_pay_scene 
       ,hist_prec_version 
       ,hist_version_per 
       ,info_1_dif 
       ,info_1_opdif 
       ,info_2_dif 
       ,info_2_opdif 
       ,info1_n_perh 
       ,info1_n_perhop 
       ,info2_n_perh 
       ,info2_n_perhop 
       ,ip_city 
       ,ip_city_dif 
       ,ip_city_opdif 
       ,ip_mycert_c 
       ,ip_mycert_p 
       ,ip_myphone_c 
       ,ip_myphone_p 
       ,ip_n_perh 
       ,ip_n_perhop 
       ,ip_opdif 
       ,ip_prov 
       ,ip_prov_dif 
       ,ip_prov_opdif 
       ,ipcity_n_perh 
       ,ipcity_n_perhop 
       ,ipprov_n_perh 
       ,ipprov_n_perhop 
       ,log_hist_prec_card_bin_prov 
       ,log_hist_prec_card_cert_city 
       ,log_hist_prec_card_cert_no 
       ,log_hist_prec_card_mobile_prov 
       ,log_hist_prec_cert_city 
       ,log_hist_prec_device_sign 
       ,log_hist_prec_info_2 
       ,log_hist_prec_ip_city 
       ,log_hist_prec_ip_prov 
       ,log_hist_prec_is_one_people 
       ,log_hist_prec_mobile_oper_platform 
       ,log_hist_prec_network 
       ,log_hist_prec_operation_channel 
       ,log_hist_prec_pay_scene 
       ,log_hist_prec_version 
       ,mer_sp 
       ,mobile_oper_platform 
       ,mobileop_n_perh 
       ,mobileop_n_perhop 
       ,multi_user 
       ,net_n_perh 
       ,net_n_perhop 
       ,network 
       ,network_dif 
       ,network_opdif 
       ,null_all 
       ,null_card 
       ,null_event 
       ,null_ip 
       ,o_hist_high_proba 
       ,opcha_n_perhop 
       ,opchannel_dif 
       ,operation_channel 
       ,operation_channel_dif_opdif 
       ,pay_oper_merge 
       ,pay_scene 
       ,payprov_n_perhop 
       ,payscene_n_perh 
       ,payscene_n_perhop 
       ,prec_client_ip_by_event_id_count 
       ,prec_device_sign_by_network_count 
       ,prec_divide_client_ip_count 
       ,prec_divide_ip_prov_count 
       ,prec_ip_prov_by_info_2_count 
       ,prec_operation_channel_by_client_ip_count 
       ,prec_operation_channel_by_event_id_count 
       ,prec_operation_channel_by_network_count 
       ,prec_operation_channel_by_user_id_count 
       ,prec_opposing_id_by_ip_city_count 
       ,prec_opposing_id_by_operation_channel_count 
       ,prec_pay_scene_by_client_ip_count 
       ,prec_pay_scene_by_mobile_oper_platform_count 
       ,prec_pay_scene_by_operation_channel_count 
       ,prec_user_id_by_amt_count 
       ,prec_user_id_by_event_id_count 
       ,prec_user_id_by_opposing_id_count 
       ,prec_user_id_by_pay_scene_count 
       ,ratio_amtop 
       ,rn 
       ,score_over00_05_max_last 
       ,score_over00_05_sum_last 
       ,score_over00_50_max_last 
       ,score_over00_50_sum_last 
       ,segmentation 
       ,u_hist_high_proba 
       ,u_of_o_perc 
       ,user_opid_dis_perc 
       ,version 
       ,version_dif 
       ,version_n_perh 
       ,version_n_perhop 
       ,week_no 
       ,win_avg_1d_now_num 
       ,win_avg_3d_now_num 
       ,win_avg_5d_now_num 
       ,win_avg_7d_now_num 
       ,win_gmt_date_1_num_zero 
       ,win_gmt_date_3_num_zero 
       ,win_gmt_date_5_num_zero 
       ,win_gmt_date_7_num_zero 
       ,win_oppid_card_bin_prov_1_num 
       ,win_oppid_card_bin_prov_7_num 
       ,win_oppid_card_mobile_city_7_num 
       ,win_oppid_card_mobile_prov_3_num 
       ,win_opposing_id_3_num 
       ,win_opposing_id_5_num 
       ,win_opposing_id_7_num 
   FROM train_fillna_low_all_feas_0825
;


CREATE TABLE IF NOT EXISTS train_high_feas AS
  SELECT event_id 
       ,new_is_fraud 
       ,amt 
       ,amt_r 
       ,card_bin_prov 
       ,card_cert_city 
       ,card_cert_prov 
       ,card_mobile_city 
       ,card_mobile_prov 
       ,cert_city 
       ,cert_myphone_c 
       ,cert_myphone_p 
       ,cert_prov 
       ,de_n_perh 
       ,de_n_perhop 
       ,deal_cnt_inf 
       ,deal_cnt_ratio 
       ,device_dif 
       ,device_opdif 
       ,device_sign 
       ,event_rank_day 
       ,event_rank_dayop 
       ,gmt_day_of_month 
       ,gmt_day_of_week 
       ,gmt_hour 
       ,h_dif 
       ,high_1_rato 
       ,high_3_rato 
       ,high_5_rato 
       ,high_7_rato 
       ,high_freq 
       ,his_high_fix 
       ,hist_amt_per 
       ,hist_card_bin_city_per 
       ,hist_card_bin_prov_per 
       ,hist_card_cert_city_per 
       ,hist_card_cert_no_per 
       ,hist_card_cert_prov_per 
       ,hist_card_mobile_city_per 
       ,hist_card_mobile_prov_per 
       ,hist_cert_city_per 
       ,hist_cert_prov_per 
       ,hist_client_ip_per 
       ,hist_device_sign_per 
       ,hist_info_1_per 
       ,hist_info_2_per 
       ,hist_ip_city_per 
       ,hist_ip_prov_per 
       ,hist_mobile_oper_platform_per 
       ,hist_network_per 
       ,hist_operation_channel_per 
       ,hist_pay_scene_per 
       ,hist_prec_amt 
       ,hist_prec_card_bin_city 
       ,hist_prec_card_bin_prov 
       ,hist_prec_card_cert_city 
       ,hist_prec_card_cert_no 
       ,hist_prec_card_cert_prov 
       ,hist_prec_card_mobile_city 
       ,hist_prec_card_mobile_prov 
       ,hist_prec_cert_city 
       ,hist_prec_cert_prov 
       ,hist_prec_city 
       ,hist_prec_client_ip 
       ,hist_prec_device_sign 
       ,hist_prec_info_1 
       ,hist_prec_info_1_income_card_no 
       ,hist_prec_info_2 
       ,hist_prec_info_2_mobile_oper_platform 
       ,hist_prec_ip_city 
       ,hist_prec_ip_prov 
       ,hist_prec_is_peer_pay 
       ,hist_prec_mobile_oper_platform 
       ,hist_prec_network 
       ,hist_prec_operation_channel 
       ,hist_prec_pay_scene 
       ,hist_prec_version 
       ,hist_version_per 
       ,info_1_dif 
       ,info_1_opdif 
       ,info_2_dif 
       ,info_2_opdif 
       ,info1_n_perh 
       ,info1_n_perhop 
       ,info2_n_perh 
       ,info2_n_perhop 
       ,ip_city 
       ,ip_city_dif 
       ,ip_city_opdif 
       ,ip_mycert_c 
       ,ip_mycert_p 
       ,ip_myphone_c 
       ,ip_myphone_p 
       ,ip_n_perh 
       ,ip_n_perhop 
       ,ip_opdif 
       ,ip_prov 
       ,ip_prov_dif 
       ,ip_prov_opdif 
       ,ipcity_n_perh 
       ,ipcity_n_perhop 
       ,ipprov_n_perh 
       ,ipprov_n_perhop 
       ,log_hist_prec_card_bin_prov 
       ,log_hist_prec_card_cert_city 
       ,log_hist_prec_card_cert_no 
       ,log_hist_prec_card_mobile_prov 
       ,log_hist_prec_cert_city 
       ,log_hist_prec_device_sign 
       ,log_hist_prec_info_2 
       ,log_hist_prec_ip_city 
       ,log_hist_prec_ip_prov 
       ,log_hist_prec_is_one_people 
       ,log_hist_prec_mobile_oper_platform 
       ,log_hist_prec_network 
       ,log_hist_prec_operation_channel 
       ,log_hist_prec_pay_scene 
       ,log_hist_prec_version 
       ,mer_sp 
       ,mobile_oper_platform 
       ,mobileop_n_perh 
       ,mobileop_n_perhop 
       ,multi_user 
       ,net_n_perh 
       ,net_n_perhop 
       ,network 
       ,network_dif 
       ,network_opdif 
       ,null_all 
       ,null_card 
       ,null_event 
       ,null_ip 
       ,o_hist_high_proba 
       ,opcha_n_perhop 
       ,opchannel_dif 
       ,operation_channel 
       ,operation_channel_dif_opdif 
       ,pay_oper_merge 
       ,pay_scene 
       ,payprov_n_perhop 
       ,payscene_n_perh 
       ,payscene_n_perhop 
       ,prec_client_ip_by_event_id_count 
       ,prec_device_sign_by_network_count 
       ,prec_divide_client_ip_count 
       ,prec_divide_ip_prov_count 
       ,prec_ip_prov_by_info_2_count 
       ,prec_operation_channel_by_client_ip_count 
       ,prec_operation_channel_by_event_id_count 
       ,prec_operation_channel_by_network_count 
       ,prec_operation_channel_by_user_id_count 
       ,prec_opposing_id_by_ip_city_count 
       ,prec_opposing_id_by_operation_channel_count 
       ,prec_pay_scene_by_client_ip_count 
       ,prec_pay_scene_by_mobile_oper_platform_count 
       ,prec_pay_scene_by_operation_channel_count 
       ,prec_user_id_by_amt_count 
       ,prec_user_id_by_event_id_count 
       ,prec_user_id_by_opposing_id_count 
       ,prec_user_id_by_pay_scene_count 
       ,ratio_amtop 
       ,rn 
       ,score_over00_05_max_last 
       ,score_over00_05_sum_last 
       ,score_over00_50_max_last 
       ,score_over00_50_sum_last 
       ,segmentation 
       ,u_hist_high_proba 
       ,u_of_o_perc 
       ,user_opid_dis_perc 
       ,version 
       ,version_dif 
       ,version_n_perh 
       ,version_n_perhop 
       ,week_no 
       ,win_avg_1d_now_num 
       ,win_avg_3d_now_num 
       ,win_avg_5d_now_num 
       ,win_avg_7d_now_num 
       ,win_gmt_date_1_num_zero 
       ,win_gmt_date_3_num_zero 
       ,win_gmt_date_5_num_zero 
       ,win_gmt_date_7_num_zero 
       ,win_oppid_card_bin_prov_1_num 
       ,win_oppid_card_bin_prov_7_num 
       ,win_oppid_card_mobile_city_7_num 
       ,win_oppid_card_mobile_prov_3_num 
       ,win_opposing_id_3_num 
       ,win_opposing_id_5_num 
       ,win_opposing_id_7_num 
   FROM train_fillna_high_all_feas_0825
;


CREATE TABLE IF NOT EXISTS train_low_feas AS
  SELECT event_id 
       ,new_is_fraud 
       ,amt 
       ,amt_r 
       ,card_bin_prov 
       ,card_cert_city 
       ,card_cert_prov 
       ,card_mobile_city 
       ,card_mobile_prov 
       ,cert_city 
       ,cert_myphone_c 
       ,cert_myphone_p 
       ,cert_prov 
       ,de_n_perh 
       ,de_n_perhop 
       ,deal_cnt_inf 
       ,deal_cnt_ratio 
       ,device_dif 
       ,device_opdif 
       ,device_sign 
       ,event_rank_day 
       ,event_rank_dayop 
       ,gmt_day_of_month 
       ,gmt_day_of_week 
       ,gmt_hour 
       ,h_dif 
       ,high_1_rato 
       ,high_3_rato 
       ,high_5_rato 
       ,high_7_rato 
       ,high_freq 
       ,his_high_fix 
       ,hist_amt_per 
       ,hist_card_bin_city_per 
       ,hist_card_bin_prov_per 
       ,hist_card_cert_city_per 
       ,hist_card_cert_no_per 
       ,hist_card_cert_prov_per 
       ,hist_card_mobile_city_per 
       ,hist_card_mobile_prov_per 
       ,hist_cert_city_per 
       ,hist_cert_prov_per 
       ,hist_client_ip_per 
       ,hist_device_sign_per 
       ,hist_info_1_per 
       ,hist_info_2_per 
       ,hist_ip_city_per 
       ,hist_ip_prov_per 
       ,hist_mobile_oper_platform_per 
       ,hist_network_per 
       ,hist_operation_channel_per 
       ,hist_pay_scene_per 
       ,hist_prec_amt 
       ,hist_prec_card_bin_city 
       ,hist_prec_card_bin_prov 
       ,hist_prec_card_cert_city 
       ,hist_prec_card_cert_no 
       ,hist_prec_card_cert_prov 
       ,hist_prec_card_mobile_city 
       ,hist_prec_card_mobile_prov 
       ,hist_prec_cert_city 
       ,hist_prec_cert_prov 
       ,hist_prec_city 
       ,hist_prec_client_ip 
       ,hist_prec_device_sign 
       ,hist_prec_info_1 
       ,hist_prec_info_1_income_card_no 
       ,hist_prec_info_2 
       ,hist_prec_info_2_mobile_oper_platform 
       ,hist_prec_ip_city 
       ,hist_prec_ip_prov 
       ,hist_prec_is_peer_pay 
       ,hist_prec_mobile_oper_platform 
       ,hist_prec_network 
       ,hist_prec_operation_channel 
       ,hist_prec_pay_scene 
       ,hist_prec_version 
       ,hist_version_per 
       ,info_1_dif 
       ,info_1_opdif 
       ,info_2_dif 
       ,info_2_opdif 
       ,info1_n_perh 
       ,info1_n_perhop 
       ,info2_n_perh 
       ,info2_n_perhop 
       ,ip_city 
       ,ip_city_dif 
       ,ip_city_opdif 
       ,ip_mycert_c 
       ,ip_mycert_p 
       ,ip_myphone_c 
       ,ip_myphone_p 
       ,ip_n_perh 
       ,ip_n_perhop 
       ,ip_opdif 
       ,ip_prov 
       ,ip_prov_dif 
       ,ip_prov_opdif 
       ,ipcity_n_perh 
       ,ipcity_n_perhop 
       ,ipprov_n_perh 
       ,ipprov_n_perhop 
       ,log_hist_prec_card_bin_prov 
       ,log_hist_prec_card_cert_city 
       ,log_hist_prec_card_cert_no 
       ,log_hist_prec_card_mobile_prov 
       ,log_hist_prec_cert_city 
       ,log_hist_prec_device_sign 
       ,log_hist_prec_info_2 
       ,log_hist_prec_ip_city 
       ,log_hist_prec_ip_prov 
       ,log_hist_prec_is_one_people 
       ,log_hist_prec_mobile_oper_platform 
       ,log_hist_prec_network 
       ,log_hist_prec_operation_channel 
       ,log_hist_prec_pay_scene 
       ,log_hist_prec_version 
       ,mer_sp 
       ,mobile_oper_platform 
       ,mobileop_n_perh 
       ,mobileop_n_perhop 
       ,multi_user 
       ,net_n_perh 
       ,net_n_perhop 
       ,network 
       ,network_dif 
       ,network_opdif 
       ,null_all 
       ,null_card 
       ,null_event 
       ,null_ip 
       ,o_hist_high_proba 
       ,opcha_n_perhop 
       ,opchannel_dif 
       ,operation_channel 
       ,operation_channel_dif_opdif 
       ,pay_oper_merge 
       ,pay_scene 
       ,payprov_n_perhop 
       ,payscene_n_perh 
       ,payscene_n_perhop 
       ,prec_client_ip_by_event_id_count 
       ,prec_device_sign_by_network_count 
       ,prec_divide_client_ip_count 
       ,prec_divide_ip_prov_count 
       ,prec_ip_prov_by_info_2_count 
       ,prec_operation_channel_by_client_ip_count 
       ,prec_operation_channel_by_event_id_count 
       ,prec_operation_channel_by_network_count 
       ,prec_operation_channel_by_user_id_count 
       ,prec_opposing_id_by_ip_city_count 
       ,prec_opposing_id_by_operation_channel_count 
       ,prec_pay_scene_by_client_ip_count 
       ,prec_pay_scene_by_mobile_oper_platform_count 
       ,prec_pay_scene_by_operation_channel_count 
       ,prec_user_id_by_amt_count 
       ,prec_user_id_by_event_id_count 
       ,prec_user_id_by_opposing_id_count 
       ,prec_user_id_by_pay_scene_count 
       ,ratio_amtop 
       ,rn 
       ,score_over00_05_max_last 
       ,score_over00_05_sum_last 
       ,score_over00_50_max_last 
       ,score_over00_50_sum_last 
       ,segmentation 
       ,u_hist_high_proba 
       ,u_of_o_perc 
       ,user_opid_dis_perc 
       ,version 
       ,version_dif 
       ,version_n_perh 
       ,version_n_perhop 
       ,week_no 
       ,win_avg_1d_now_num 
       ,win_avg_3d_now_num 
       ,win_avg_5d_now_num 
       ,win_avg_7d_now_num 
       ,win_gmt_date_1_num_zero 
       ,win_gmt_date_3_num_zero 
       ,win_gmt_date_5_num_zero 
       ,win_gmt_date_7_num_zero 
       ,win_oppid_card_bin_prov_1_num 
       ,win_oppid_card_bin_prov_7_num 
       ,win_oppid_card_mobile_city_7_num 
       ,win_oppid_card_mobile_prov_3_num 
       ,win_opposing_id_3_num 
       ,win_opposing_id_5_num 
       ,win_opposing_id_7_num 
   FROM testb_new_low_all_feas_0828
;


CREATE TABLE IF NOT EXISTS test_high_feas AS
  SELECT event_id 
       ,new_is_fraud 
       ,amt 
       ,amt_r 
       ,card_bin_prov 
       ,card_cert_city 
       ,card_cert_prov 
       ,card_mobile_city 
       ,card_mobile_prov 
       ,cert_city 
       ,cert_myphone_c 
       ,cert_myphone_p 
       ,cert_prov 
       ,de_n_perh 
       ,de_n_perhop 
       ,deal_cnt_inf 
       ,deal_cnt_ratio 
       ,device_dif 
       ,device_opdif 
       ,device_sign 
       ,event_rank_day 
       ,event_rank_dayop 
       ,gmt_day_of_month 
       ,gmt_day_of_week 
       ,gmt_hour 
       ,h_dif 
       ,high_1_rato 
       ,high_3_rato 
       ,high_5_rato 
       ,high_7_rato 
       ,high_freq 
       ,his_high_fix 
       ,hist_amt_per 
       ,hist_card_bin_city_per 
       ,hist_card_bin_prov_per 
       ,hist_card_cert_city_per 
       ,hist_card_cert_no_per 
       ,hist_card_cert_prov_per 
       ,hist_card_mobile_city_per 
       ,hist_card_mobile_prov_per 
       ,hist_cert_city_per 
       ,hist_cert_prov_per 
       ,hist_client_ip_per 
       ,hist_device_sign_per 
       ,hist_info_1_per 
       ,hist_info_2_per 
       ,hist_ip_city_per 
       ,hist_ip_prov_per 
       ,hist_mobile_oper_platform_per 
       ,hist_network_per 
       ,hist_operation_channel_per 
       ,hist_pay_scene_per 
       ,hist_prec_amt 
       ,hist_prec_card_bin_city 
       ,hist_prec_card_bin_prov 
       ,hist_prec_card_cert_city 
       ,hist_prec_card_cert_no 
       ,hist_prec_card_cert_prov 
       ,hist_prec_card_mobile_city 
       ,hist_prec_card_mobile_prov 
       ,hist_prec_cert_city 
       ,hist_prec_cert_prov 
       ,hist_prec_city 
       ,hist_prec_client_ip 
       ,hist_prec_device_sign 
       ,hist_prec_info_1 
       ,hist_prec_info_1_income_card_no 
       ,hist_prec_info_2 
       ,hist_prec_info_2_mobile_oper_platform 
       ,hist_prec_ip_city 
       ,hist_prec_ip_prov 
       ,hist_prec_is_peer_pay 
       ,hist_prec_mobile_oper_platform 
       ,hist_prec_network 
       ,hist_prec_operation_channel 
       ,hist_prec_pay_scene 
       ,hist_prec_version 
       ,hist_version_per 
       ,info_1_dif 
       ,info_1_opdif 
       ,info_2_dif 
       ,info_2_opdif 
       ,info1_n_perh 
       ,info1_n_perhop 
       ,info2_n_perh 
       ,info2_n_perhop 
       ,ip_city 
       ,ip_city_dif 
       ,ip_city_opdif 
       ,ip_mycert_c 
       ,ip_mycert_p 
       ,ip_myphone_c 
       ,ip_myphone_p 
       ,ip_n_perh 
       ,ip_n_perhop 
       ,ip_opdif 
       ,ip_prov 
       ,ip_prov_dif 
       ,ip_prov_opdif 
       ,ipcity_n_perh 
       ,ipcity_n_perhop 
       ,ipprov_n_perh 
       ,ipprov_n_perhop 
       ,log_hist_prec_card_bin_prov 
       ,log_hist_prec_card_cert_city 
       ,log_hist_prec_card_cert_no 
       ,log_hist_prec_card_mobile_prov 
       ,log_hist_prec_cert_city 
       ,log_hist_prec_device_sign 
       ,log_hist_prec_info_2 
       ,log_hist_prec_ip_city 
       ,log_hist_prec_ip_prov 
       ,log_hist_prec_is_one_people 
       ,log_hist_prec_mobile_oper_platform 
       ,log_hist_prec_network 
       ,log_hist_prec_operation_channel 
       ,log_hist_prec_pay_scene 
       ,log_hist_prec_version 
       ,mer_sp 
       ,mobile_oper_platform 
       ,mobileop_n_perh 
       ,mobileop_n_perhop 
       ,multi_user 
       ,net_n_perh 
       ,net_n_perhop 
       ,network 
       ,network_dif 
       ,network_opdif 
       ,null_all 
       ,null_card 
       ,null_event 
       ,null_ip 
       ,o_hist_high_proba 
       ,opcha_n_perhop 
       ,opchannel_dif 
       ,operation_channel 
       ,operation_channel_dif_opdif 
       ,pay_oper_merge 
       ,pay_scene 
       ,payprov_n_perhop 
       ,payscene_n_perh 
       ,payscene_n_perhop 
       ,prec_client_ip_by_event_id_count 
       ,prec_device_sign_by_network_count 
       ,prec_divide_client_ip_count 
       ,prec_divide_ip_prov_count 
       ,prec_ip_prov_by_info_2_count 
       ,prec_operation_channel_by_client_ip_count 
       ,prec_operation_channel_by_event_id_count 
       ,prec_operation_channel_by_network_count 
       ,prec_operation_channel_by_user_id_count 
       ,prec_opposing_id_by_ip_city_count 
       ,prec_opposing_id_by_operation_channel_count 
       ,prec_pay_scene_by_client_ip_count 
       ,prec_pay_scene_by_mobile_oper_platform_count 
       ,prec_pay_scene_by_operation_channel_count 
       ,prec_user_id_by_amt_count 
       ,prec_user_id_by_event_id_count 
       ,prec_user_id_by_opposing_id_count 
       ,prec_user_id_by_pay_scene_count 
       ,ratio_amtop 
       ,rn 
       ,score_over00_05_max_last 
       ,score_over00_05_sum_last 
       ,score_over00_50_max_last 
       ,score_over00_50_sum_last 
       ,segmentation 
       ,u_hist_high_proba 
       ,u_of_o_perc 
       ,user_opid_dis_perc 
       ,version 
       ,version_dif 
       ,version_n_perh 
       ,version_n_perhop 
       ,week_no 
       ,win_avg_1d_now_num 
       ,win_avg_3d_now_num 
       ,win_avg_5d_now_num 
       ,win_avg_7d_now_num 
       ,win_gmt_date_1_num_zero 
       ,win_gmt_date_3_num_zero 
       ,win_gmt_date_5_num_zero 
       ,win_gmt_date_7_num_zero 
       ,win_oppid_card_bin_prov_1_num 
       ,win_oppid_card_bin_prov_7_num 
       ,win_oppid_card_mobile_city_7_num 
       ,win_oppid_card_mobile_prov_3_num 
       ,win_opposing_id_3_num 
       ,win_opposing_id_5_num 
       ,win_opposing_id_7_num 
   FROM testb_new_high_all_feas_0828
;


